[build]
  command = "node generate.js && SITE_URL=$DEPLOY_PRIME_URL node absolutize.js && node minify.js && SITE_URL=$DEPLOY_PRIME_URL node sitemap.js"
  publish = "."

[build.environment]
  NODE_VERSION = "18"

[context.production.environment]
  SITE_URL = "https://www.travelplugguide.com"
